//string FirstName = "Bob";
//int widgetsSold = 7;
//Console.WriteLine(FirstName + " sold " + (widgetsSold + 7) + " widgets.");
//Console.WriteLine("Modules of 200 / 5 : " + (200 % 5));
//Console.WriteLine("Modulues of 7 / 5: " + (7 % 5));
//double banana = System.Math.Pow(2,4);
//Console.WriteLine(banana);
//Console.WriteLine(System.Math.Pow(3,2));
//Console.WriteLine(Math.Pow(3, 2));
//int value = 1;
//value = value + 1;
//Console.WriteLine("First increment: " + value);
//value += 3;
//Console.WriteLine("Second increment: " + value);
//value++;
//Console.WriteLine("Third increment: " + value);
//value = value - 1;
//Console.WriteLine("First decrement: " + value);
//value -= 1;
//Console.WriteLine("Second decrement: " + value);
//value--;
//Console.WriteLine("Third decrement: " + value);
//Console.WriteLine("First: " + value);
//Console.WriteLine("Second: " + value++);
//Console.WriteLine("Third: " + value);
//Console.WriteLine("Fourth: " + ++value);
int fahrenheit = 94;
Console.WriteLine("The temperature is " + ((fahrenheit - 32m) * (5.0m / 9.0m)) + " Celsius");